[package]
name = "dumbpipe"
version = "0.3.0"
edition = "2021"
authors = ["Rüdiger Klaehn <rklaehn@protonmail.com>", "n0 team"]
keywords = ["netcat", "cli", "network", "p2p", "holepunching"]
categories = ["network-programming"]
license = "Apache-2.0/MIT"
repository = "https://github.com/n0-computer/dumb-pipe"
description = "A cli tool to pipe data over the network, with NAT hole punching"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
base32 = "0.4.0"
clap = { version = "4.4.10", features = ["derive"] }
data-encoding = "2.5.0"
hex = "0.4.3"
iroh-net = { git = "https://github.com/n0-computer/iroh", branch = "main" }
postcard = "1.0.8"
quinn = "0.10.2"
serde = "1.0.193"
tokio = { version = "1.34.0", features = ["full"] }
tokio-util = "0.7.10"
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }

[dev-dependencies]
duct = "0.13.6"
nix = { version = "0.27", features = ["signal", "process"] }
rand = "0.8.5"
