[package]
name = "dumbpipe"
version = "0.1.0"
edition = "2021"
authors = ["Rüdiger Klaehn <rklaehn@protonmail.com>"]
keywords = ["netcat", "cli", "network", "p2p", "holepunching"]
categories = ["network-programming"]
license = "Apache-2.0/MIT"
repository = "https://github.com/n0-computer/dumb-pipe"
description = "A cli tool to pipe data over the network, with NAT hole punching"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
base32 = "0.4.0"
clap = { version = "4.4.10", features = ["derive"] }
data-encoding = "2.5.0"
iroh-net = "0.11.0"
postcard = "1.0.8"
quinn = "0.10.2"
serde = "1.0.193"
tokio = { version = "1.34.0", features = ["full"] }
tokio-util = "0.7.10"
tracing-subscriber = "0.3.18"
